import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex gap-20 min-h-screen md:flex md:flex-col`}
      >
        <div className="fixed w-12 min-h-full flex md:min-h-0 md:w-full">
          <Navbar />
        </div>

        <div className=" p-9 ml-16  md:m-0 md:mt-14">{children}</div>
      </body>
    </html>
  );
}
